DROP TABLE IF EXISTS EMPLOYEE
GO

CREATE TABLE EMPLOYEE (EMPID INT IDENTITY(1,1) PRIMARY KEY,
ENAME VARCHAR(200),
SALARY MONEY,
DEPARTMENT VARCHAR(500))

GO

INSERT INTO EMPLOYEE(ENAME,DEPARTMENT,SALARY)
VALUES
('E1','IT',560000),
('E2','HR',960000),
('E3','AUTO-MOBILE',59030),
('E4','IT',560000)

GO 
--DROP PROCEDURE IF EXISTS GETEMPLOYEE

--GO

--CREATE PROCEDURE GETEMPLOYEE


--AS
--BEGIN
--UPDATE EMPLOYEE SET SALARY = SALARY + 100 WHERE DEPARTMENT ='IT'
--SELECT ENAME,SALARY,DEPARTMENT FROM EMPLOYEE WHERE DEPARTMENT='IT'

--END

--GO
--EXEC GETEMPLOYEE
--DROP PROCEDURE IF EXISTS UPDATEEMPLOYEE
--GO
--CREATE PROCEDURE UPDATEEMPLOYEE
--@EMPID INT ,
--@INCSALARY MONEY

--AS
--BEGIN
--UPDATE EMPLOYEE
--SET SALARY=SALARY + @INCSALARY
--SELECT * FROM EMPLOYEE WHERE EMPID=@EMPID
--END
--GO
--EXEC UPDATEEMPLOYEE @EMPID=2,@INCSALARY=200
--GO
--EXEC UPDATEEMPLOYEE @EMPID=3,@INCSALARY=20000000
--DROP PROCEDURE IF EXISTS GETSAL;
--GO

--CREATE PROCEDURE GETSAL
--    @EMPID INT,
--    @ESALARY MONEY OUTPUT
--AS
--BEGIN
--    SELECT @ESALARY = SALARY
--    FROM EMPLOYEE
--    WHERE EMPID = @EMPID;
--END;
--GO

--DECLARE @EMPSAL MONEY
--EXEC GETSAL
--@EMPID=2,
--@ESALARY=@EMPSAL OUTPUT;
--SELECT @EMPSAL AS EmployeeSalary
GO
DROP PROCEDURE IF EXISTS ManageEmployee
GO
CREATE PROCEDURE ManageEmployee
@EID INT=NULL,
@Ename VARCHAR(100)=NULL,
@Esalary Money=20000,
@Dept VARCHAR(200)=NULL,
@Action VARCHAR(200)
AS
BEGIN
SELECT * FROM EMPLOYEE;
IF @Action ='Insert'
   BEGIN 
   INSERT INTO EMPLOYEE(SALARY,ENAME,DEPARTMENT)VALUES
   (@Esalary,@Ename,@Dept)
   END
ELSE IF @Action='Update'
   BEGIN
   UPDATE EMPLOYEE SET SALARY=@Esalary,DEPARTMENT=@Dept WHERE EMPID=@EID
   END
ELSE IF @Action ='Get'
   BEGIN
   SELECT EMPID,ENAME,DEPARTMENT,SALARY,
   CASE 
   WHEN SALARY > 20000 THEN  'HIGH SALARY'
   ELSE 'NORMAL SALARY'
   END
   FROM EMPLOYEE
   WHERE(@EID IS NULL OR @EID=EMPID)
   END
ELSE 
   BEGIN
     PRINT 'Invalid imput'
   END
END

GO

EXEC ManageEmployee @Action='Insert',@Ename='E5',@Esalary=20900,@Dept='hr'
GO
EXEC ManageEmployee @Action='Insert', @Ename='E6', @Dept='Finance';
GO
EXEC ManageEmployee @Action='Update', @EID=2, @Esalary=999999, @Dept='HR';
GO
EXEC ManageEmployee @Action='Get';
GO
EXEC ManageEmployee @Action='Get',@EID=2;

