CREATE TABLE EMPLOYEE (EMPID INT IDENTITY(1,1) PRIMARY KEY,
ENAME VARCHAR(200),
SALARY MONEY,
DEPARTMENT VARCHAR(500))

GO

INSERT INTO EMPLOYEE(ENAME,DEPARTMENT,SALARY)
VALUES
('E1','IT',560000),
('E2','HR',960000),
('E3','AUTO-MOBILE',59030),
('E4','IT',560000)

GO 

CREATE PROCEDURE GETEMPLOYEE
@EMPID INT=NULL,
@ENAME VARCHAR(300)=NULL

AS
BEGIN
SELECT EMPID,ENAME,SALARY,DEPARTMENT FROM EMPLOYEE WHERE (@EMPID IS NULL OR EMPID=@EMPID) 
AND (@ENAME IS NULL OR ENAME=@ENAME)
END

GO

EXEC GETEMPLOYEE @EMPID=3

EXEC GETEMPLOYEE @ENAME='E2';

EXEC GETEMPLOYEE @ENAME='E4',@EMPID=4;
EXEC GETEMPLOYEE ;